### ISSUE TITLE
Server main crash

### ISSUE THREAD

**Issue by ByMofm** [alkemyTech/OT173-server-js#27]
Al iniciar el servidor se genera un error, el problema se encuentra en /models/testimonials.
-Linea 16:  hace un user.init cuando deberia hacer un Testimony.init
-linea 13:  user.belongsTo tambien modificar eso.

**Comment by cabellonic** [comment]
A mi me toca hacer el PUT de los testimonios y, aún cambiando el código, con el nombre actual del modelo sequelize me tira error porque en vez de revisar la tabla `testimonials` revisa la tabla `testimonies`, que no existe.

### Cambios propuestos

- Cambiar el nombre del modelo a `Testimonial` para que sequelize lo pluralice como `testimonials` en la DB, ejecutando los comandos:

`npx sequelize-cli model:generate --name Testimonial --attributes name:string,image:string,content:text`
Y `npx sequelize-cli db:migrate` **[*]**

- Generar un seeder apropiado con el comando `npx sequelize-cli seed:generate --name demo-testimonial` con un contenido como el siguiente:

```js
'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Testimonials", [{
       name: "Nombre del testimonio",
       image: "https://picsum.photos/200/300",
       content: "Contenido del testimonio.",
       createdAt: new Date(),
       updatedAt: new Date(),
    }], {})
   },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
```

**Pull Request con los cambios sugeridos:** https://github.com/alkemyTech/OT173-server-js/pull/28

**[*] Nota de implementarse mi PR:** Si ya ejecutaron las migraciones y los seeders con el modelo que da conflictos, eliminen las tablas `sequelizemeta` y `testimonials` y vuelvan a generarlas.
