### ISSUE TITLE
Fix endpoint actualización de novedades

### ISSUE THREAD

**Issue by FedeMontenegro** [alkemyTech/OT173-server-js#52]
Se necesitan actualizar el endpoint de actualización de novedad en los siguientes puntos:
- Solicitar el `id` de la categoría a la tabla `categorías`.
- Es más conveniente realizar un spread a la hora de cargar los datos que llegan del body, ya que no necesariamente va a ser información de todas las columnas de la tabla `categorías`.
- Insertar correctamente el `id` de la categoría que se obtiene como respuesta a la solicitud de la misma.
- En la cláusula `catch`, el error enviado como respuesta está mencionado como `error`, pero el parámetro que se está recibiendo es `err`.

* Estado actual:

```
const updateNew = async (req, res, next) => {
  const { name, content, image, type } = req.body;
  const { id } = req.params;
  try {
    const updatedNew = await Entries.update(
      {
        name,
        content,
        image,
        type,
      },
      {
        where: {
          id: id,
        },
        returning: true,
        plain: true,
      }
    );
    if (!updatedNew)
      return res
        .status(httpCodes.UNAUTHORIZED)
        .json({ msg: "Invalid username or password" });
    res.status(httpCodes.OK).json(updatedNew);
  } catch (err) {
    res.status(httpCodes.BAD_REQUEST).json({ error, ok: false });
  }
}
```
* Solución propuesta:

```
const updateNew = async (req, res, next) => {
  const { category } = req.body;
  const { id } = req.params;
  try {
    let categoryFromDB = {}

    if(category) {

      categoryFromDB = await Categories.findOne({
        where: { name: category }
      });
      
      if (!categoryFromDB)
        return res
          .status(httpCodes.BAD_REQUEST)
          .json({ msg: 'Category not found' });
    }

    const updatedNew = await Entries.update(
      {
        ...req.body,
        categoryId: categoryFromDB?.dataValues?.id
      },
      {
        where: {
          id: id
        },
        returning: true,
        plain: true,
      }
    );
    if (!updatedNew){
      return res
        .status(httpCodes.UNAUTHORIZED)
        .json({ msg: "Invalid username or password" });
    }
    return res.status(httpCodes.OK).json({msg:"Updated successfully", updatedNew});
  } catch (err) {
    
    return res.status(httpCodes.BAD_REQUEST).json({ err, ok: false });
  }
```

**Comment by cabellonic** [comment]
Diría que sequelize lo contempla y la entrada se actualiza igual, pero fijate que si hacés esto en el update:
```js
const updatedNew = await Entries.update(
  {
    ...req.body, // <<
    categoryId: categoryFromDB?.dataValues?.id
  }
  //...
);
```
estarías pasándole también la posible propiedad `category` con el nombre de la categoría, y eso no estaría incluido en el modelo de `Entries` en la base de datos.
Se tendría que hacer algo como `const { category, ...newsBody } = req.body;` y pasar ese `...newsBody` en su lugar.
Creo que no da ningún error, pero entiendo que es lo que querías evitar desestructurando el `req.body`.
